/**
 * Agent permission feature keys.
 * Each entry defines the key stored in user_permissions.feature,
 * a human-readable label, and the category grouping.
 */
export const AGENT_PERMISSION_CATEGORIES = [
  {
    id: 'dashboard',
    label: 'Dashboard & Analytics',
    icon: '📊',
    permissions: [
      { key: 'dashboard_view',              label: 'View Dashboard' },
      { key: 'dashboard_executive',         label: 'View Executive Summary' },
      { key: 'dashboard_properties',        label: 'View Properties Section' },
      { key: 'dashboard_clients',           label: 'View Clients Section' },
      { key: 'dashboard_inquiries',         label: 'View Inquiries Section' },
      { key: 'dashboard_financial',         label: 'View Financial Section' },
      { key: 'dashboard_agents',            label: 'View Agents Section' },
      { key: 'dashboard_branches',          label: 'View Branches Section' },
      { key: 'dashboard_chat',              label: 'View Chat Metrics Section' },
      { key: 'dashboard_compliance',        label: 'View Compliance Section' },
      { key: 'dashboard_documents',         label: 'View Documents Section' },
      { key: 'dashboard_events',            label: 'View Events Section' },
      { key: 'dashboard_services',          label: 'View Services Section' },
      { key: 'dashboard_website',           label: 'View Website Analytics Section' },
      { key: 'dashboard_training',          label: 'View Training Section' },
      { key: 'dashboard_activity',          label: 'View Activity Log Section' },
      { key: 'dashboard_export',            label: 'Export Dashboard Data' },
    ],
  },
  {
    id: 'properties',
    label: 'Properties',
    icon: '🏠',
    permissions: [
      { key: 'properties_view',             label: 'View Properties' },
      { key: 'properties_create',           label: 'Create Properties' },
      { key: 'properties_edit',             label: 'Edit Properties' },
      { key: 'properties_delete',           label: 'Delete Properties' },
      { key: 'properties_approve',          label: 'Approve/Reject Properties' },
      { key: 'properties_feature',          label: 'Feature/Unfeature Properties' },
      { key: 'properties_owner_details',    label: 'View Owner Details on Properties' },
      { key: 'properties_export',           label: 'Export Properties (CSV/Excel)' },
      { key: 'properties_images',           label: 'Manage Property Images' },
      { key: 'properties_documents',        label: 'Manage Property Documents' },
      { key: 'properties_matching',         label: 'Property Matching / Auto-Match' },
      { key: 'properties_valuations',       label: 'View/Request Property Valuations' },
      { key: 'properties_virtual_tours',    label: 'Manage Virtual Tours' },
      { key: 'properties_policies',         label: 'Manage Property Policies' },
    ],
  },
  {
    id: 'clients',
    label: 'Clients',
    icon: '👥',
    permissions: [
      { key: 'clients_view',                label: 'View Clients' },
      { key: 'clients_create',              label: 'Create Clients' },
      { key: 'clients_edit',                label: 'Edit Clients' },
      { key: 'clients_delete',              label: 'Delete Clients' },
      { key: 'clients_matches',             label: 'View Client Matches' },
      { key: 'clients_recalc',              label: 'Recalculate Matches' },
      { key: 'clients_communication',       label: 'Client Communication (Email/SMS/WhatsApp)' },
      { key: 'clients_documents',           label: 'Manage Client Documents' },
    ],
  },
  {
    id: 'owners',
    label: 'Owners',
    icon: '🏢',
    permissions: [
      { key: 'owners_view',                 label: 'View Owners' },
      { key: 'owners_create',               label: 'Create Owners' },
      { key: 'owners_edit',                 label: 'Edit Owners' },
      { key: 'owners_delete',               label: 'Delete Owners' },
      { key: 'owners_communication',        label: 'Owner Communication' },
      { key: 'owners_documents',            label: 'Manage Owner Documents' },
    ],
  },
  {
    id: 'contacts',
    label: 'Contacts',
    icon: '📇',
    permissions: [
      { key: 'contacts_view',               label: 'View Contacts' },
      { key: 'contacts_create',             label: 'Create Contacts' },
      { key: 'contacts_edit',               label: 'Edit Contacts' },
      { key: 'contacts_delete',             label: 'Delete Contacts' },
    ],
  },
  {
    id: 'agents',
    label: 'Agents / Team',
    icon: '🧑‍💼',
    permissions: [
      { key: 'agents_view',                 label: 'View Agents' },
      { key: 'agents_create',               label: 'Add Agents' },
      { key: 'agents_edit',                 label: 'Edit Agents' },
      { key: 'agents_delete',               label: 'Delete Agents' },
      { key: 'agents_approve',              label: 'Approve/Reject Agent Registrations' },
      { key: 'agents_permissions',          label: 'Manage Agent Permissions' },
      { key: 'agents_performance',          label: 'View Agent Performance' },
      { key: 'agents_commission',           label: 'Agent Commission Management' },
      { key: 'agents_schedule',             label: 'Agent Schedule Management' },
      { key: 'team_view',                   label: 'View Team Page' },
    ],
  },
  {
    id: 'inquiries',
    label: 'Inquiries',
    icon: '📋',
    permissions: [
      { key: 'inquiries_view_all',          label: 'View All Inquiries' },
      { key: 'inquiries_view_own',          label: 'View Own Inquiries Only' },
      { key: 'inquiries_create',            label: 'Create Inquiries' },
      { key: 'inquiries_assign',            label: 'Assign Inquiries' },
      { key: 'inquiries_close',             label: 'Close Inquiries' },
      { key: 'inquiries_manage',            label: 'Manage All Inquiries' },
    ],
  },
  {
    id: 'services',
    label: 'Services',
    icon: '🛎️',
    permissions: [
      { key: 'services_view',               label: 'View Services' },
      { key: 'services_create',             label: 'Create Services' },
      { key: 'services_edit',               label: 'Edit Services' },
      { key: 'services_delete',             label: 'Delete Services' },
      { key: 'services_assign',             label: 'Assign Services' },
      { key: 'services_pricing',            label: 'Manage Service Pricing' },
      { key: 'services_car_rental',         label: 'Car Rental Services' },
      { key: 'services_boat_rental',        label: 'Boat Rental Services' },
      { key: 'services_tours',              label: 'Tours & Excursions' },
      { key: 'services_relocation',         label: 'Relocation Services' },
      { key: 'services_cleaning',           label: 'Cleaning Services' },
      { key: 'services_maintenance',        label: 'Maintenance Services' },
      { key: 'services_key_holding',        label: 'Key Holding Services' },
      { key: 'services_concierge',          label: 'Concierge Services' },
      { key: 'services_airport_transfers',  label: 'Airport Transfer Services' },
      { key: 'services_insurance',          label: 'Insurance Services' },
      { key: 'services_legal',              label: 'Legal Services' },
      { key: 'services_photography',        label: 'Photography & Media Services' },
    ],
  },
  {
    id: 'chat',
    label: 'Chat & Messaging',
    icon: '💬',
    permissions: [
      { key: 'chat_view',             label: 'Access Chat' },
      { key: 'chat_direct_message',   label: 'Send Direct Messages' },
      { key: 'chat_group_channels',   label: 'Access Group Channels' },
      { key: 'chat_property_updates', label: 'View Property Updates Feed' },
      { key: 'chat_create_channels',  label: 'Create Chat Channels' },
      // Legacy keys kept for backwards-compat
      { key: 'chat_internal',         label: 'Access Internal Chat (legacy)' },
      { key: 'chat_manage_channels',  label: 'Manage Chat Channels' },
      { key: 'chat_direct_messages',  label: 'Direct Messages (legacy)' },
      { key: 'announcements_send',    label: 'Create/Send Announcements' },
      { key: 'announcements_view',    label: 'View Announcements' },
      { key: 'announcements_edit',    label: 'Edit Announcements' },
      { key: 'announcements_delete',  label: 'Delete Announcements' },
    ],
  },
  {
    id: 'announcements',
    label: 'Announcements',
    icon: '📢',
    permissions: [
      { key: 'announcements_view',          label: 'View Announcements' },
      { key: 'announcements_create',        label: 'Create Announcements' },
      { key: 'announcements_edit',          label: 'Edit Announcements' },
      { key: 'announcements_delete',        label: 'Delete Announcements' },
      { key: 'announcements_target',        label: 'Target Announcements (Advanced)' },
      { key: 'announcements_pin',           label: 'Pin/Unpin Announcements' },
    ],
  },
  {
    id: 'documents',
    label: 'Documents / Files',
    icon: '📄',
    permissions: [
      { key: 'documents_view',              label: 'View Documents' },
      { key: 'documents_upload',            label: 'Upload Documents' },
      { key: 'documents_delete',            label: 'Delete Documents' },
      { key: 'documents_file_manager',      label: 'Manage File Manager' },
      { key: 'files_view',                  label: 'View File Manager' },
      { key: 'files_upload',                label: 'Upload Files' },
      { key: 'files_delete',                label: 'Delete Files' },
    ],
  },
  {
    id: 'calendar',
    label: 'Calendar / Events',
    icon: '📅',
    permissions: [
      { key: 'calendar_view',               label: 'View Calendar' },
      { key: 'calendar_create',             label: 'Create Events' },
      { key: 'calendar_edit',               label: 'Edit Events' },
      { key: 'calendar_delete',             label: 'Delete Events' },
      { key: 'calendar_schedule',           label: 'Schedule Viewings' },
      { key: 'calendar_meetings',           label: 'Schedule Meetings' },
      { key: 'events_view',                 label: 'View Events' },
      { key: 'events_manage',               label: 'Create/Edit/Delete Events' },
    ],
  },
  {
    id: 'training',
    label: 'Training',
    icon: '🎓',
    permissions: [
      { key: 'training_view',               label: 'View Training Courses' },
      { key: 'training_manage',             label: 'Create/Edit/Delete Training Courses' },
    ],
  },
  {
    id: 'branches',
    label: 'Branches',
    icon: '🏪',
    permissions: [
      { key: 'branches_view',               label: 'View Branches' },
      { key: 'branches_create',             label: 'Add Branches' },
      { key: 'branches_edit',               label: 'Edit Branches' },
      { key: 'branches_delete',             label: 'Delete Branches' },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    icon: '⚖️',
    permissions: [
      { key: 'admin_compliance',            label: 'View Compliance' },
      { key: 'compliance_aml_kyc',          label: 'Manage AML/KYC' },
      { key: 'compliance_reports',          label: 'Generate Compliance Reports' },
    ],
  },
  {
    id: 'financial',
    label: 'Financial',
    icon: '💰',
    permissions: [
      { key: 'financial_own_commission',    label: 'View Own Commission' },
      { key: 'financial_all_commission',    label: 'View All Commissions' },
      { key: 'financial_revenue',           label: 'View Revenue Dashboard' },
      { key: 'financial_mortgage_calc',     label: 'Mortgage Calculator' },
      { key: 'financial_payments',          label: 'Manage Payments' },
      { key: 'financial_invoices_view',     label: 'View Invoices' },
      { key: 'financial_invoices_generate', label: 'Generate Invoices' },
      { key: 'financial_reports',           label: 'Financial Reports' },
      { key: 'mortgage_calculator_view',    label: 'View Mortgage Calculator' },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    icon: '📣',
    permissions: [
      { key: 'marketing_listings',          label: 'Manage Listings on Public Website' },
      { key: 'marketing_social',            label: 'Social Media Integration' },
      { key: 'marketing_email_campaigns',   label: 'Email Marketing Campaigns' },
      { key: 'marketing_print',             label: 'Print Material Management' },
      { key: 'marketing_seo',               label: 'SEO Management' },
      { key: 'marketing_website_content',   label: 'Website Content Management' },
    ],
  },
  {
    id: 'public_website',
    label: 'Public Website',
    icon: '🌐',
    permissions: [
      { key: 'website_properties',          label: 'Manage Public Property Listings' },
      { key: 'website_services',            label: 'Manage Services Page' },
      { key: 'website_about',               label: 'Manage About Page' },
      { key: 'website_contact',             label: 'Manage Contact Page' },
      { key: 'website_blog',                label: 'Manage Blog/News' },
      { key: 'website_testimonials',        label: 'Manage Testimonials' },
    ],
  },
  {
    id: 'administration',
    label: 'Administration / Settings',
    icon: '⚙️',
    permissions: [
      { key: 'admin_agents',                label: 'Manage Agents (legacy)' },
      { key: 'admin_branches',              label: 'Manage Branches (legacy)' },
      { key: 'admin_activity_logs',         label: 'View Activity Logs' },
      { key: 'admin_settings',              label: 'System Settings' },
      { key: 'admin_user_management',       label: 'User Management' },
      { key: 'admin_role_management',       label: 'Role Management' },
      { key: 'admin_backup',                label: 'Backup Management' },
      { key: 'admin_audit_logs',            label: 'Audit Logs' },
      { key: 'admin_api_keys',              label: 'API Keys' },
      { key: 'admin_templates',             label: 'Email/SMS Templates' },
      { key: 'admin_notifications',         label: 'Notification Settings' },
      { key: 'admin_branding',              label: 'Branding/Theme Customization' },
      { key: 'activity_view',               label: 'View Activity Log' },
      { key: 'settings_view',               label: 'View Settings' },
    ],
  },
  {
    id: 'integrations',
    label: 'Integrations (Future)',
    icon: '🔌',
    permissions: [
      { key: 'integrations_crm',            label: 'CRM Integrations' },
      { key: 'integrations_api_access',     label: 'API Access' },
      { key: 'integrations_webhooks',       label: 'Webhook Management' },
      { key: 'integrations_portal_syndication', label: 'Third-party Portal Syndication' },
      { key: 'integrations_mls',            label: 'MLS Integration' },
    ],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    icon: '🔔',
    permissions: [
      { key: 'notifications_view',                label: 'View Notifications' },
      { key: 'notifications_property_events',     label: 'Property Event Notifications' },
      { key: 'notifications_client_events',       label: 'Client Event Notifications' },
      { key: 'notifications_agent_events',        label: 'Agent Event Notifications' },
      { key: 'notifications_branch_events',       label: 'Branch Event Notifications' },
      { key: 'notifications_inquiry_events',      label: 'Inquiry Event Notifications' },
      { key: 'notifications_announcement_events', label: 'Announcement Notifications' },
      { key: 'notifications_system_alerts',       label: 'System Alert Notifications' },
      { key: 'notifications_chat_events',         label: 'Chat Message Notifications' },
    ],
  },
  {
    id: 'reports',
    label: 'Reports & Analytics (Future)',
    icon: '📈',
    permissions: [
      { key: 'reports_generate',            label: 'Generate Reports' },
      { key: 'reports_analytics_dashboard', label: 'View Analytics Dashboard' },
      { key: 'reports_performance',         label: 'Performance Reports' },
      { key: 'reports_market',              label: 'Market Reports' },
      { key: 'reports_revenue',             label: 'Revenue Reports' },
      { key: 'reports_view',                label: 'View Reports Page' },
    ],
  },
];

/** Flat array of all permission keys */
export const ALL_PERMISSION_KEYS = AGENT_PERMISSION_CATEGORIES.flatMap(cat =>
  cat.permissions.map(p => p.key)
);
